//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activity_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Schedule1 { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> Room { get; set; }
        public string Teacher { get; set; }
    }
}
